pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
           steps {
               echo 'Installing dependencies'
                sh '''
                    #!/bin/sh
                    pip3 install -r requirements.txt
                '''
           } 
        }    

        stage('Run Learning Pipeline (Preprocess + Learning + Evaluation)') {
            // Train the model
           steps {
                echo 'Starting Run Learning Pipeline Stage...'
                 
                // sh '''
                //     #!/bin/sh

                //     python3 ./ml/KNN.py
                // '''
                echo 'Run Learning Pipeline finished successfully.'
            } // steps
        } // stage
        stage("Test Infraestructure Code"){
            steps{
                echo 'Starting Test Infraestructure Code Stage...' 
                 sh '''
                    #!/bin/sh
                    python3 -m pytest --cov=./ --cov-report=xml ./
                '''
                cobertura coberturaReportFile: 'coverage.xml'
                echo 'Test Infraestructure Code finished successfully.'
            }
        }
    } // stages
}